application: subhasisnotebook
version: 3
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
- url: /favicon\.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon\.ico
 
- url: /temp/  
  static_dir: static/temp
 
- url: /js/
  static_dir: static/js

- url: /img/
  static_dir: static/images

- url: /css/
  mime_type: text/css
  static_dir: static/css

- url: /fonts/
  static_dir: static/fonts

- url: /partials/
  static_dir: static/partials

- url: /_include/  
  static_dir: static/_include

- url: /profile
  script: main.application

- url: /admin/.*
  script: main.application
  login: admin  

- url: /.*
  static_files: template/index.html
  upload: template/index\.html



  

  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: "1.1.7"
- name: endpoints
  version: latest
# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest